# Generated by Django 3.0.8 on 2020-09-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200918_0605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
